image: python:3.12-slim

stages:
  - linting
  - type-checking
  - testing


.base:
  tags:
    - docker
  before_script:
    - pip install poetry
  rules:
    - changes:
      - "**/*.py"
      - ".gitlab-ci.yml"
      - "services/**/poetry.lock"
      when: on_success
    - changes:
      - "**.md"
      when: never
    - when: never


linting_flow:
  extends: .base
  stage: linting
  script:
    - cd services/flow-service
    - poetry install --no-root
    - poetry run ruff check src/


mypy_flow:
  extends: .base
  stage: type-checking
  script:
    - cd services/flow-service
    - poetry install --no-root
    - poetry run mypy src/


tests_flow:
  extends: .base
  stage: testing
  script:
    - cd services/flow-service
    - poetry install --no-root
    - poetry run pytest
  coverage: '/TOTAL.*\s+(\d+%)$/'


linting_scoring:
  extends: .base
  stage: linting
  script:
    - cd services/scoring-service
    - poetry install --no-root
    - poetry run ruff check src/


mypy_scoring:
  extends: .base
  stage: type-checking
  script:
    - cd services/scoring-service
    - poetry install --no-root
    - poetry run mypy src/


tests_scoring:
  extends: .base
  stage: testing
  script:
    - cd services/scoring-service
    - poetry install --no-root
    - poetry run pytest
  coverage: '/TOTAL.*\s+(\d+%)$/'


linting_data:
  extends: .base
  stage: linting
  script:
    - cd services/user-data-service
    - poetry install --no-root
    - poetry run ruff check src/


mypy_data:
  extends: .base
  stage: type-checking
  script:
    - cd services/user-data-service
    - poetry install --no-root
    - poetry run mypy src/


tests_data:
  extends: .base
  stage: testing
  services:
    - name: postgres:17-alpine
      alias: postgres_test
  variables:
    POSTGRES_DB: test
    POSTGRES_USER: test
    POSTGRES_PASSWORD: test
    DATABASE_URL: "postgresql+asyncpg://test:test@postgres_test:5432/test"
  script:
    - cd services/user-data-service
    - poetry install --no-root
    - poetry run alembic upgrade head
    - poetry run pytest
  coverage: '/TOTAL.*\s+(\d+%)$/'


cache:
  key:
    files:
      - poetry.lock
    prefix: "$CI_COMMIT_REF_SLUG"
  paths:
    - root/.cache/pypoetry
    - root/.cache/pip