apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "user-data-service.fullname.release" . }}
  namespace: {{ .Values.student.namespace }}
  labels:
    {{ include "user-data-service.selectorLabels.custom" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "user-data-service.selectorLabels.custom" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "user-data-service.selectorLabels.custom" . | nindent 8}}
    spec:
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets.name }}
      containers:
        - name: {{ include "user-data-service.name" . }}
          image: "{{ .Values.image.repository}}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          command: ["sh", "-c"]
          args:
            - "python -m alembic upgrade head && python -m uvicorn app.service:app --host 0.0.0.0 --port 8000"
          resources:
            {{ toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: {{ .Values.probe.liveness.path }}
              port: {{ .Values.service.port }}
            initialDelaySeconds: {{ .Values.probe.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probe.liveness.periodSeconds }}
            failureThreshold: {{ .Values.probe.liveness.failureThreshold }}
          
          readinessProbe:
            httpGet:
              path: {{ .Values.probe.readiness.path }}
              port: {{ .Values.service.port }}
            initialDelaySeconds: {{ .Values.probe.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probe.readiness.periodSeconds }}
            failureThreshold: {{ .Values.probe.readiness.failureThreshold }}
            
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.dbCredentialName }}
                  key: {{ .Values.secrets.dataBaseUrl }}
            - name: KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: {{ include "user-data-service.configmap.name" . }}
                  key: KAFKA_BOOTSTRAP_SERVERS
            - name: KAFKA_TOPIC
              valueFrom:
                configMapKeyRef:
                  name: {{ include "user-data-service.configmap.name" . }}
                  key: KAFKA_TOPIC
            - name: KAFKA_GROUP_ID
              valueFrom:
                configMapKeyRef:
                  name: {{ include "user-data-service.configmap.name" . }}
                  key: KAFKA_GROUP_ID