apiVersion: apps/v1
kind: Deployment
metadata:
  name: flow-selection-service-kbatrakov
  namespace: test
  labels:
    student: kbatrakov
    app: flow-selection-service
spec:
  replicas: 1
  selector:
    matchLabels:
      student: kbatrakov
      app: flow-selection-service
  template:
    metadata:
      labels:
        student: kbatrakov
        app: flow-selection-service
    spec:
      imagePullSecrets:
        - name: regcred-kbatrakov 
      containers:
        - name: flow-selection-service
          image: shift.gitlab.yandexcloud.net:5050/shift-python/y2025/homeworks/batrakov-k/main_shift_project/flow-service:latest
          imagePullPolicy: Always
          resources:
            limits:
              memory: "100Mi"
              cpu: "100m"
            requests:
              memory: "50Mi"
              cpu: "50m"
          ports:
            - containerPort: 8000

          livenessProbe:
            httpGet:
              path: /up
              port: 8000
            initialDelaySeconds: 20
            periodSeconds: 2
            failureThreshold: 5
          
          readinessProbe:
            httpGet:
              path: /ready
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 3
            failureThreshold: 5
            
          env:
            - name: DATA_SERVICE_MAX_ATTEMPTS
              valueFrom:
                configMapKeyRef:
                  name: app-config-kbatrakov
                  key: DATA_SERVICE_MAX_ATTEMPTS
            - name: DATA_SERVICE_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config-kbatrakov
                  key: DATA_SERVICE_BASE_URL
            - name: DATA_SERVICE_DELAY
              valueFrom:
                configMapKeyRef:
                  name: app-config-kbatrakov
                  key: DATA_SERVICE_DELAY
            - name: DATA_SERVICE_TIMEOUT
              valueFrom:
                configMapKeyRef:
                  name: app-config-kbatrakov
                  key: DATA_SERVICE_TIMEOUT
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config-kbatrakov
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config-kbatrakov
                  key: REDIS_PORT
            - name: REDIS_TTL
              valueFrom:
                configMapKeyRef:
                name: app-config-kbatrakov
                key: REDIS_TTL
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials-kbatrakov
                  key: REDIS_PASSWORD
                
