apiVersion: v1
kind: Secret
metadata:
  name: redis-credentials-kbatrakov
  namespace: test
  labels:
    student: kbatrakov
    app: flow-selection-service
stringData:
  REDIS_PASSWORD: "shift_2025_python"
