apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-data-service-kbatrakov
  namespace: test
  labels:
    student: kbatrakov
    app: user-data-service
spec:
  replicas: 1
  selector:
    matchLabels:
      student: kbatrakov
      app: user-data-service
  template:
    metadata:
      labels:
        student: kbatrakov
        app: user-data-service
    spec:
      imagePullSecrets:
        - name: regcred-kbatrakov 
      containers:
        - name: user-data-service
          image: shift.gitlab.yandexcloud.net:5050/shift-python/y2025/homeworks/batrakov-k/main_shift_project/data-service:latest
          imagePullPolicy: Always
          resources:
            limits:
              memory: "100Mi"
              cpu: "100m"
            requests:
              memory: "50Mi"
              cpu: "50m"
          ports:
            - containerPort: 8000
          command: ["sh", "-c"]
          args:
            - "python -m alembic upgrade head && python -m uvicorn app.service:app --host 0.0.0.0 --port 8000"
         
          livenessProbe:
            httpGet:
              path: /up
              port: 8000
            initialDelaySeconds: 50
            periodSeconds: 2
            failureThreshold: 5
          
          readinessProbe:
            httpGet:
              path: /ready
              port: 8000
            initialDelaySeconds: 60
            periodSeconds: 3
            failureThreshold: 5
            
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: db-credential-kbatrakov
                  key: DATABASE_URL
            
            - name: KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: app-config-kbatrakov
                  key: KAFKA_BOOTSTRAP_SERVERS
            - name: KAFKA_TOPIC
              valueFrom:
                configMapKeyRef:
                  name: app-config-kbatrakov
                  key: KAFKA_TOPIC
            - name: KAFKA_GROUP_ID
              valueFrom:
                configMapKeyRef:
                  name: app-config-kbatrakov
                  key: KAFKA_GROUP_ID