apiVersion: v1
kind: Secret
metadata:
  name: db-credentials-kbatrakov
  namespace: test
  labels:
    student: kbatrakov
    app: user-data-service
stringData:
  DATABASE_URL: "postgresql+asyncpg://kbatrakov:BCDN6erqyBhT6k8Z@postgres-service.infra.svc.cluster.local:5432/kbatrakov"
