apiVersion: v1
kind: Service
metadata:
  name: scoring-service-kbatrakov
  namespace: test
  labels:
    student: kbatrakov
    app: scoring-service
spec:
  selector:
    app: scoring-service
    student: kbatrakov
  ports:
      - port: 8000
        targetPort: 8000
