data_service:
  base_url: 'http://localhost:8002'
  timeout: 5
  retries:
    max_attempts: 2
    delay: 1

kafka:
  bootstrap_servers: 'localhost:9092'
  topic: 'scoring_results'
  request_timeout_ms: 1000